package com.kpmg.aml.screening.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.LocalDate;
import java.time.LocalDateTime;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.Setter;

/**
 * JPA entity for aml.screening_exceptions.
 *
 * One row per exception customer per screening run.  Normal customers
 * (action = SCREEN) do NOT appear here — they are covered by
 * sch_screening_cus / sch_screening_match.
 *
 * Primary key is a UUIDv7 string generated by UuidV7.java — no @GeneratedValue.
 *
 * @author user
 */
@Getter
@Setter
@Entity
@Table(name = "screening_exceptions", schema = "aml")
public class ScreeningExceptionEntity {

    // ── Identity ──────────────────────────────────────────────────────────────

    @Id
    @Column(name = "id", nullable = false, length = 36)
    private String id;

    @Column(name = "run_id", nullable = false, length = 20)
    private String runId;

    // ── Customer ──────────────────────────────────────────────────────────────

    @Column(name = "client_id", nullable = false, length = 50)
    private String clientId;

    @Column(name = "original_name", nullable = false, length = 1000)
    private String originalName;

    @Column(name = "normalized_name", length = 1000)
    private String normalizedName;              // null for SKIPPED records

    @Column(name = "id_number", length = 50)
    private String idNumber;                    // raw NIC / ID from source

    @Column(name = "entity_type", nullable = false, length = 20)
    private String entityType;

    @Column(name = "date_of_birth")
    private LocalDate dateOfBirth;              // secondary FP identifier

    @Column(name = "nationality", length = 3)
    private String nationality;                 // ISO Alpha-3 (LKA if valid SL NIC)

    // ── Classification ────────────────────────────────────────────────────────

    @Column(name = "reason_code", nullable = false, length = 50)
    private String reasonCode;                  // NameNormalizer CODE_* constant

    @Column(name = "action", nullable = false, length = 30)
    private String action;

    @Column(name = "screening_mode", length = 20)
    private String screeningMode;               // NORMAL / RESTRICTED / NIC_ONLY; null for SKIPPED

    @Column(name = "note", columnDefinition = "text")
    private String note;                        // human-readable for compliance

    // ── Per-list screening results ────────────────────────────────────────────

    @Column(name = "fiu_ind", length = 20)
    private String fiuInd;

    @Column(name = "fiu_org", length = 20)
    private String fiuOrg;

    @Column(name = "un_consolidated", length = 20)
    private String unConsolidated;

    @Column(name = "local_watch", length = 20)
    private String localWatch;

    @Column(name = "lexis_nexis", length = 20)
    private String lexisNexis;

    @Column(name = "dow_jones", length = 20)
    private String dowJones;

    // ── Screening execution context ───────────────────────────────────────────

    @Column(name = "screened_at")
    private LocalDateTime screenedAt;           // null for SKIPPED customers

    @Column(name = "match_count")
    private Integer matchCount;                 // Solr candidates before Python scoring; null if SKIPPED

    // ── Infrastructure failure context ────────────────────────────────────────
    // Only populated when at least one list column = FAILED.
    // First-write-wins: set once on the first list failure; subsequent failures
    // in the same run do not overwrite (see ScreeningExceptionWriter.setListFailed).

    @Column(name = "failure_reason", length = 50)
    private String failureReason;

    @Column(name = "failure_details", columnDefinition = "text")
    private String failureDetails;

    // ── Audit ─────────────────────────────────────────────────────────────────

    @Setter(AccessLevel.NONE)                   // DB-managed via DEFAULT CURRENT_TIMESTAMP
    @Column(name = "created_at", nullable = false, updatable = false, insertable = false)
    private LocalDateTime createdAt;

    // ── Constructors ──────────────────────────────────────────────────────────

    public ScreeningExceptionEntity() {}
}
